jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: postgres
      password: password
      port: 5432
      dbname: postgres
      schema: jaffle_shop
      threads: 4
    prod:
      type: postgres
      host: postgres
      user: postgres
      password: password
      port: 5432
      dbname: postgres
      schema: prod
      threads: 4
